apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: influxdbv1-helm-values
  namespace: influx
spec:
  keys:
    - values.yaml
  path: secrets/influx/influxdbv1/influxdbv1-helm-values
  type: Opaque
