---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: appdaemon
  namespace: appdaemon
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: UTC
      HA_URL: "https://ha.sievert.fun" 
      DASH_URL: "https://appdaemon.sievert.fun"
    image:
      pullPolicy: IfNotPresent
      repository: acockburn/appdaemon
      tag: 4.2.1
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/internal-hostname: appdaemon.sievert.fun
        hosts:
          - host: appdaemon.sievert.fun
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - appdaemon.sievert.fun
            secretName: appdaemon-cert
    persistence:
      config:
        enabled: true
        mountPath: /conf
    service:
      main:
        ports:
          http:
            port: 5050
