---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.releases.hashicorp.com
      chart: vault
      version: 0.20.1
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      interval: 5m
  values:
    server:
      dataStorage:
        enabled: true
        storageClass: "qnap-nfs-client"
      extraVolumes:
        - type: secret
          name: kms-vault
          path: /vault/userconfig
      tolerations: |
        - key: "arm"
          operator: "Exists"
      annotations:
        backup.velero.io/backup-volumes: data
      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 256Mi
    ui:
      enabled: true
