---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-operator
  namespace: vault
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.releases.hashicorp.com
      chart: vault-secrets-operator
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: ricoberger
        namespace: flux-system
      interval: 5m
  values:
    install:
      crds: Create
    upgrade:
      crds: CreateReplace
#    image:
#      repository: ricoberger/vault-secrets-operator
#      tag: 1.2.3
    replicaCount: 1
    deploymentStrategy:
      type: Recreate
    vault:
      address: "http://vault:8200"
      authMethod: kubernetes
      kubernetesPath: auth/kubernetes
      kubernetesRole: vault-secrets-operator
      reconciliationTime: "300"