---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://metallb.github.io/metallb
      chart: metallb
      version: 0.15.2
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      interval: 5m
  values:
    configInline:
      address-pools:
        - addresses:
            - 192.168.5.10-192.168.5.99
          name: default
          protocol: layer2
    controller:
      affinity: {}
      enabled: true
      image:
        pullPolicy: null
        repository: quay.io/metallb/controller
        tag: null
      livenessProbe:
        enabled: true
        failureThreshold: 3
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      logLevel: info
      nodeSelector: {}
      podAnnotations: {}
      priorityClassName: ''
      readinessProbe:
        enabled: true
        failureThreshold: 3
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources: {}
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccount:
        annotations: {}
        create: true
        name: ''
      tolerations: []
    existingConfigMap: ''
    fullnameOverride: ''
    imagePullSecrets: []
    nameOverride: ''
    prometheus:
      metricsPort: 7472
      namespace: ''
      podMonitor:
        additionalLabels: {}
        enabled: false
        interval: null
        jobLabel: app.kubernetes.io/name
        metricRelabelings: []
        relabelings: []
      prometheusRule:
        additionalLabels: {}
        addressPoolExhausted:
          enabled: true
          labels:
            severity: alert
        addressPoolUsage:
          enabled: true
          thresholds:
            - labels:
                severity: warning
              percent: 75
            - labels:
                severity: warning
              percent: 85
            - labels:
                severity: alert
              percent: 95
        bgpSessionDown:
          enabled: true
          labels:
            severity: alert
        configNotLoaded:
          enabled: true
          labels:
            severity: warning
        enabled: false
        extraAlerts: []
        staleConfig:
          enabled: true
          labels:
            severity: warning
      scrapeAnnotations: false
      serviceAccount: ''
    psp:
      create: true
    rbac:
      create: true
    speaker:
      affinity: {}
      enabled: true
      frr:
        enabled: false
        image:
          pullPolicy: null
          repository: quay.io/frrouting/frr
          tag: stable_7.5
        logLevel: informational
      image:
        pullPolicy: null
        repository: quay.io/metallb/speaker
        tag: null
      livenessProbe:
        enabled: true
        failureThreshold: 3
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      logLevel: info
      memberlist:
        enabled: true
        mlBindPort: 7946
      nodeSelector: {}
      podAnnotations: {}
      priorityClassName: ''
      readinessProbe:
        enabled: true
        failureThreshold: 3
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources: {}
      serviceAccount:
        annotations: {}
        create: true
        name: ''
      tolerateMaster: true
      tolerations: []
