---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bliss
  namespace: bliss
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ : America/Chicago
    image:
      pullPolicy: Always
      repository: cooperised/bliss
      tag: latest@sha256:bb63feb6da0833f2d5b94c3f9a5176580c62c2a330e9b754685c4d8d44c39819
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/internal-hostname: bliss.sievert.fun
        hosts:
          - host: bliss.sievert.fun
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - bliss.sievert.fun
            secretName: bliss-cert
    persistence:
      config:
        enabled: true
        mountPath: /config
      media:
        enabled: true
        mountPath: /media
        existingClaim: bliss-media
    service:
      main:
        ports:
          http:
            port: 3220
