---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uip
  namespace: uip
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: Secret
      name: "poller-helm-values"
      optional: false
  values:
    image:
      pullPolicy: Always
      repository: ghcr.io/unpoller/unpoller
      tag: v2.9.2@sha256:585a29a06d054749fdca4fc589209058b71df43695fffba028f6ee0a4ea0ba87
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/internal-hostname: uip.sievert.fun
        hosts:
          - host: uip.sievert.fun
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - uip.sievert.fun
            secretName: uip-cert
    persistence:
      config:
        enabled: false
        mountPath: /config
    service:
      main:
        ports:
          http:
            port: 37288
