---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mealie
  namespace: mealie
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: mealie
      version: 5.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: Secret
      name: "mealie-helm-values"
  values:
    env:
      DB_ENGINE: postgres
      TZ: UTC
      POSTGRES_DB: mealie
      POSTGRES_PASSWORD: mealie
      POSTGRES_SERVER: mealie-db-postgresql-hl
      POSTGRES_USER: mealie
    image:
      pullPolicy: IfNotPresent
      repository: hkotel/mealie
      tag: v1.0.0@sha256:86eb67572f68e1a8d306e805d7a2677c751247bd84093f4304587d0b61094d26
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/internal-hostname: food.sievert.fun
        hosts:
          - host: food.sievert.fun
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - food.sievert.fun
            secretName: food-cert
    persistence:
      config:
        enabled: true
        mountPath: /app/data/
    service:
      main:
        ports:
          http:
            port: 80
