---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: blakeblackshear
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://blakeblackshear.github.io/blakeshome-charts/
