---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: csi-driver-smb
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
