---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kavita
  namespace: kavita
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    TZ : America/Chicago
    image:
      pullPolicy: Always
      repository: kizaing/kavita
      tag: 0.7.2
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/internal-hostname: books.sievert.fun
        hosts:
          - host: books.sievert.fun
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - books.sievert.fun
            secretName: books-cert
    persistence:
      config:
        enabled: true
        mountPath: /kavita/config
        storageClass: local-path
      media:
        enabled: true
        mountPath: /media/books
        existingClaim: kavita-books
    service:
      main:
        ports:
          http:
            port: 5000
