---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: overseerr
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: overseerr
      version: 5.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    env:
      LOG_LEVEL: info
      TZ: UTC
    image:
      pullPolicy: IfNotPresent
      repository: ghcr.io/sct/overseerr
      tag: 1.30.0
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/internal-hostname: overseerr.sievert.fun
        hosts:
          - host: overseerr.sievert.fun
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - overseerr.sievert.fun
            secretName: overseerr-cert
    persistence:
      config:
        enabled: true
        mountPath: /app/config
        existingClaim: overseerr-config
    service:
      main:
        ports:
          http:
            port: 5055
