---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: hajimari
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.releases.hashicorp.com
      chart: hajimari
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: UTC
    hajimari:
      customApps: []
      defaultEnable: false
      groups: []
      instanceName: null
      name: Sieverts
      namespaceSelector:
        matchNames:
          - grafana
        any: true
      title: null
    image:
      pullPolicy: IfNotPresent
      repository: ghcr.io/toboshii/hajimari
      tag: v0.1.0
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/internal-hostname: hajimari.sievert.fun
        hosts:
          - host: hajimari.sievert.fun
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - hajimari.sievert.fun
            secretName: hajimari-cert
    persistence:
      data:
        enabled: true
        existingClaim: hajimari
    service:
      main:
        ports:
          http:
            port: 3000
    serviceAccount:
      create: true