---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: sonarr
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 16.2.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: UTC
    image:
      pullPolicy: IfNotPresent
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.8.1507
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/internal-hostname: sonarr.sievert.fun
        hosts:
          - host: sonarr.sievert.fun
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - sonarr.sievert.fun
            secretName: sonarr-cert
    metrics:
      enabled: false
      exporter:
        env:
          additionalMetrics: false
          port: 9794
          unknownQueueItems: false
        image:
          pullPolicy: IfNotPresent
          repository: ghcr.io/onedr0p/exportarr
          tag: v0.6.1
      prometheusRule:
        enabled: false
        labels: {}
        rules: []
      serviceMonitor:
        interval: 3m
        labels: {}
        scrapeTimeout: 1m
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config
      media:
        enabled: true
        mountPath: /media
        existingClaim: sonarr-media
    probes:
      liveness:
        custom: true
        enabled: true
        spec:
          exec:
            command:
              - /usr/bin/env
              - bash
              - '-c'
              - >-
                curl --fail localhost:8989/api/v3/system/status?apiKey=`IFS=\> &&
                while read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi;
                done < /config/config.xml`
          failureThreshold: 5
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
    service:
      main:
        ports:
          http:
            port: 8989
