---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tautulli
  namespace: plex
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: tautulli
      version: 11.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: UTC
    image:
      pullPolicy: IfNotPresent
      repository: ghcr.io/k8s-at-home/tautulli
      tag: v2.10.5
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/internal-hostname: tautulli.sievert.fun
        hosts:
          - host: tautulli.sievert.fun
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - tautulli.sievert.fun
            secretName: tautulli-cert
    persistence:
      config:
        enabled: true
    service:
      main:
        ports:
          http:
            port: 8181
