---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: emqx
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://repos.emqx.io/charts
      chart: emqx
      version: 5.0.14
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
      interval: 5m
  values:
    recreatePods: true
    persistance:
      enabled: true
      storageClassName: "qnap-nfs-client"
