---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: emqx
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://repos.emqx.io/charts
      chart: emqx
      version: 5.1.2
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: emqx/emqx
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: "5.0.16-alpine"
    recreatePods: true
    persistance:
      enabled: true
      storageClassName: "qnap-nfs-client"
    ingress:
      ## ingress for EMQX Dashboard
      dashboard:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/internal-hostname: emqx.sievert.fun
        path: /
        pathType: ImplementationSpecific
        hosts:
          - emqx.sievert.fun
        tls:
          - hosts:
            - emqx.sievert.fun
            secretName: esp-code
    service:
      ## Service type
      ##
      type: LoadBalancer
      loadBalancerIP: 192.168.5.16
      annotations:
        external-dns.alpha.kubernetes.io/hostname: mqtt.sievert.fun
        external-dns.alpha.kubernetes.io/target: 192.168.5.16
      ## Port for MQTT
      ##
      mqtt: 1883
      ## Port for MQTT(SSL)
      ##
      mqttssl: 8883
      ## Port for WebSocket/HTTP
      ##
      ws: 8083
      ## Port for WSS/HTTPS
      ##
      wss: 8084
      ## Port for dashboard and API
      ##
      dashboard: 18083
      ## Port for dashboard and API over HTTPS
