---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: emqx
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://repos.emqx.io/charts
      chart: emqx
      version: 5.0.14
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
      interval: 5m
  values:
    recreatePods: true
    persistance:
      enabled: true
      storageClassName: "qnap-nfs-client"
    ingress:
      ## ingress for EMQX Dashboard
      dashboard:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/internal-hostname: emqx.sievert.fun
        path: /
        pathType: ImplementationSpecific
        hosts:
          - emqx.emqx.local
        tls:
          - hosts:
            - emqx.sievert.fun
            secretName: esp-code
