---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: scim
  namespace: northstar
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: op-scim-bridge
      version: 10.4.2
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: flux-system
      interval: 5m
  values:
    scim:
      ingress:
        enabled: true
        className: ""
        annotations: {}
        hosts:
          - host: northstar.sievert.fun
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - secretName: scim-tls
            hosts:
              - northstar.sievert.fun