---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: navidrome
  namespace: music
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: navidrome
      version: 6.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    env:
      ND_ENABLETRANSCODINGCONFIG: 'true'
      ND_LOGLEVEL: info
      ND_MUSICFOLDER: /music
      ND_SESSIONTIMEOUT: 24h
      TZ: UTC
    image:
      pullPolicy: IfNotPresent
      repository: deluan/navidrome
      tag: 0.50.0@sha256:2cf4442b0099a5810cfaf2aa0a6718ced41222d3c41551a8dbc4949a885bb089
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/internal-hostname: music.sievert.fun
        hosts:
          - host: music.sievert.fun
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - music.sievert.fun
            secretName: music-cert
    persistence:
      config:
        enabled: true
        mountPath: /data
      music:
        enabled: true
        mountPath: /music
        existingClaim: navidrome-music
    service:
      main:
        ports:
          http:
            port: 4533
