---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: heimdall
  namespace: heimdall
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: heimdall
      version: 8.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    env:
      PGID: '1000'
      PUID: '1000'
      TZ: UTC
    image:
      pullPolicy: IfNotPresent
      repository: linuxserver/heimdall
      tag: 2.4.12
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/internal-hostname: home.sievert.fun
        hosts:
          - host: home.sievert.fun
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - home.sievert.fun
            secretName: home-cert
    persistence:
      config:
        enabled: true
    service:
      main:
        ports:
          http:
            port: 80
