---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ha
  namespace: ha
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 13.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: app
                  operator: In
                  values:
                    - zwave-controller
    addons:
      codeserver:
        args:
          - '--auth'
          - none
          - '--user-data-dir'
          - /config/.vscode
          - '--extensions-dir'
          - /config/.vscode
        enabled: true
        volumeMounts:
          - mountPath: /config
            name: config
        image:
          repository: ghcr.io/k8s-at-home/code-server
          tag: v4.6.0@sha256:68b8d9ca3c04f3c9dc2919b4d768d343f4fa53b4abafe5f3348dd7ac292d8e51
        ingress:
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
            external-dns.alpha.kubernetes.io/internal-hostname: hacode.sievert.fun
          enabled: true
          hosts:
            - host: hacode.sievert.fun
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - hacode.sievert.fun
              secretName: ha-code
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 35m
            memory: 128Mi
        workingDir: /config
    env:
      TZ: UTC
    image:
      pullPolicy: IfNotPresent
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2023.9.1@sha256:183513a13fbcb758eb525f857cf3ec69a619a5ec27c117a2077ab2f4e7a3c052
    influxdb:
      architecture: standalone
      authEnabled: false
      database: home_assistant
      enabled: false
      persistence:
        enabled: false
    ingress:
      appdaemon:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/internal-hostname: appdaemon.sievert.fun
        hosts:
          - host: appdaemon.sievert.fun
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - appdaemon.sievert.fun
            secretName: appdaemon-cert
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/internal-hostname: ha.sievert.fun
        hosts:
          - host: ha.sievert.fun
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - ha.sievert.fun
            secretName: ha-cert
    mariadb:
      architecture: standalone
      auth:
        database: home-assistant
        password: home-assistant-pass
        rootPassword: home-assistantrootpass
        username: home-assistant
      enabled: false
      primary:
        persistence:
          enabled: true
    metrics:
      enabled: false
      prometheusRule:
        enabled: false
        labels: {}
        rules: []
      serviceMonitor:
        interval: 1m
        labels: {}
        scrapeTimeout: 30s
    persistence:
      config:
        enabled: true
      usb:
        enabled: true
        hostPath: /dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_18ca9fc7e08cec11abe76ce883c5466d-if00-port0
        type: hostPath
    postgresql:
      enabled: false
      image:
        repository: bitnami/postgresql
        tag: 15.4.0@sha256:62ff441e3b5f152874ccda8198499bc5b3c7232557e1518067bdd2003c4b337b
      persistence:
        primary:
          enabled: false
      postgresqlDatabase: home-assistant
      postgresqlPassword: home-assistant-pass
      postgresqlUsername: home-assistant
    securityContext:
      privileged: true
    service:
      appdaemon:
        enabled: true
        ports:
          appdaemon:
            enabled: true
            port:  5050
            protocol: TCP
      main:
        ports:
          http:
            port: 8123
      gem:
        enabled: true
        ports:
          gem:
            enabled: true
            nodePort: 32500
            port: 32500
            protocol: TCP
        type: NodePort
    global:
      cattle:
        systemProjectId: p-dqkpq
