---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mqtt
  namespace: ha
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: mosquitto
      version: 4.8.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    auth:
      enabled: false
    image:
      pullPolicy: IfNotPresent
      repository: eclipse-mosquitto
      tag: 2.0.14
    persistence:
      configinc:
        accessMode: ReadWriteOnce
        enabled: true
        mountPath: /mosquitto/configinc
        size: 100Mi
      data:
        enabled: false
        mountPath: /mosquitto/data
    service:
      main:
        ports:
          http:
            enabled: false
          mqtt:
            enabled: true
            port: 1883
        annotations:
          external-dns.alpha.kubernetes.io/hostname: mqtt.sievert.fun
          external-dns.alpha.kubernetes.io/target: 192.168.5.16
        loadBalancerIP: 192.168.5.16
        type: LoadBalancer
