---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: sabnzbd
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sabnzbd
      version: 9.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: UTC
      HOST_WHITELIST_ENTRIES: sabnzbd.sievert.fun
    image:
      pullPolicy: IfNotPresent
      repository: ghcr.io/k8s-at-home/sabnzbd
      tag: v3.7.0@sha256:6c8bb47bbc4459bfa561d66585163d5981d1d110a0401d9f9748763e6e1f184a
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/internal-hostname: sabnzbd.sievert.fun
        hosts:
          - host: sabnzbd.sievert.fun
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - sabnzbd.sievert.fun
            secretName: ha-cert
    persistence:
      config:
        enabled: true
        existingClaim: sabnzbd-config
      downloads:
        enabled: false
        mountPath: /downloads
      media:
        enabled: true
        mountPath: /media
        existingClaim: sabnzbd-media
    service:
      main:
        ports:
          http:
            port: 8080
    deploymentStrategy:
      type: Recreate
